### ISSUE TITLE
Non-fuctional effects

### ISSUE THREAD

**Issue by dreaderinyes** [Tfarcenim/FunctionalArmorTrim#5]
I've been testing several trim related on 1.20.1 with forge 47.2.0 and verified this by making a mob pack with only this mod.
Some material effects don't seem to function at all. I tested this with iron armor and the coast trim, for the netherite and lapis I used a stone sword.

- amethyst, even with a full armor set trimmed doesn't give night vision
- copper, even with full  armor set trimmer doesn't give any swimming speed boost
- Emerald, seems to have no effect at all 
- netherite, doesn't make item fire proof but does give fire resistance
- gold does not make piglins neutral

**Comment by Tfarcenim** [comment]
I'll update to 47.1.3 and see what's up (this mod doesn't support newer forge versions than that)

**Comment by Tfarcenim** [comment]
> amethyst, even with a full armor set trimmed doesn't give night vision

It doesn't give the potion effect, but it gives the same brightness boost

> copper, even with full armor set trimmer doesn't give any swimming speed boost

If it's not doing anything, then it's a forge issue, not my mod

> Emerald, seems to have no effect at all

It's a fresh world, of course it won't have an immediate effect as it increases existing reputation by 10% and 0 increased by 10% is still 0

> netherite, doesn't make item fire proof but does give fire resistance

Verified that it still works

> gold does not make piglins neutral

Verified it still works, only 1 piece is needed

So in conclusion everything is working as intended and any problems are caused by forge or other mods
